baseurl = "https://blog.corin8823.com"
languageCode = "ja"
title = "corin8823 blog"
theme = "kiss"
disqusShortname = "corin8823"
googleAnalytics = ""

# Number of posts per page
Paginate = 10
enableRobotsTXT = true

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "corin8823 blog" # Title for home page
poweredby = false # Adds powered by Hugo and Kiss below Copyright section
related = false # Includes related articles

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]
twitter = "corin8823"
github = "corin8823"

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true